# Generated by Django 3.1.6 on 2021-02-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210203_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
