# Generated by Django 3.1.6 on 2021-02-03 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userqueries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='voters',
            field=models.ManyToManyField(blank=True, null=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
