# Generated by Django 3.1.6 on 2021-02-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userqueries', '0002_auto_20210203_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d/'),
        ),
    ]
